[project]
authors = ["Garibaldi <chanokin@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
description = "Add a short description here"
name = "topart"
platforms = ["linux-64"]
version = "0.1.0"
repository = "https://github.com/chanokin/topart"


[tasks]
main = "mojo run src/example.mojo"
test = "mojo test -I src test"

[dependencies]
max = ">=25.2.0.dev2025030205,<26"

[feature.test.tasks]
test = "pytest"

[feature.test.pypi-dependencies]
pytest = ">=8.3.5, <9"

[environments]
default = { features = [], solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
